# Generated by Django 4.2.7 on 2024-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='data_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='data_pay',
            field=models.DateField(blank=True, null=True, verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма платежа'),
        ),
    ]
