# Generated by Django 4.2.7 on 2024-03-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_lesson_options_course_price'),
        ('users', '0004_alter_payment_lesson_alter_payment_type_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.course', verbose_name='оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='data_create',
            field=models.DateField(auto_now_add=True, default='2000-01-01', verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='type_payment',
            field=models.CharField(default='Stripe', max_length=100, verbose_name='способ платежа'),
        ),
    ]
