# Generated by Django 4.2.7 on 2024-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_course_alter_payment_data_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
