version: '3'

services:
  db:
    image: postgres
    env_file:
      -  .env.prod
    environment:
      POSTGRES_DB: ${FOR_POSTGRES_NAME}
      POSTGRES_HOST: ${FOR_POSTGRES_HOST}
      POSTGRES_PORT: ${FOR_POSTGRES_PORT}
      POSTGRES_USER: ${FOR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FOR_POSTGRES_PASSWORD}

    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    depends_on:
      - db

volumes:
  pg_data:

